### ISSUE TITLE
support changing the endpoint entirely

### ISSUE THREAD

**Issue by jonsterling** [alephcloud/hs-aws-kinesis#15]
Currently, only specifying a region is possible. We should support specifying a custom endpoint, which could be useful for mocking Kinesis services for test purposes.

**Comment by jonsterling** [comment]
Closing this issue, because I intend to resolve the issue at the level of `aws-general`.

**Comment by larskuhtz** [comment]
I reopen this issue since once a `Custom EndpointDomain EndPointPort` constructor is added to `Region` in `aws-general` there is still some boilerplate needed in this package. For example here: https://github.com/alephcloud/hs-aws-kinesis/blob/master/src/Aws/Kinesis/Core.hs#L170.

**Comment by jonsterling** [comment]
Oh right, I forgot about that! Thanks for catching it.
